### ISSUE TITLE
ASet.sum/.fold pitfall; request for AList.sum/fold

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#30]
As [1; 2; 2; 2; 3] -> ASet [1; 2; 3] -> ASet.sum will be 6. In more abstract cases like: "ASet<Kartoffel> |> ASet.map (fun k -> k.Weight) |> ASet.sum" this gives unexpected results. AList seems more appropriate for this kind of use cases, but it currently has no fold operation.

**Comment by krauthaufen** [comment]
fixed via https://github.com/aardvark-platform/aardvark.base/commit/61661010ad1e7284e1007ea74f3297ba890b3d97
