### ISSUE TITLE
Aardvark.Init x86 corrupts native libs

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#41]
When starting an app with x86, Aardvark.Init will extract x86 native libs. After switching to x64 Aardvark.Init will see that the libs are there and fail loading them...

We should either separate x86 and x64 or add some other additional check to prevent this.

If we don't want to support x86 we should write a BIG warning all over the console.

**Comment by haraldsteinlechner** [comment]
still valid with new netcore3.0 mechanism?

**Comment by luithefirst** [comment]
if the netcore3.0 mechanism also extracts to aardvark-native and does not separate x86 and x64 then yes

for netframework and netcoreapp2.0 apps the same old mechnanism is used and still broken
you can go to the rendering solution and set 00 - HelloWorld (net471) to "Prefer 32-bit" and run it. if x64 was run first the aardvark-native libs will not be overwritten and the x86 app will crash. Otherwise, if changing back to x64 it will not work because the x86 dlls are still in the aardvark-native directory and will not be overwritten

**Comment by krauthaufen** [comment]
Nope, we forgot about that. I'll look into this, but 32bit compat is broken anyway for almost all aardvark components...

**Comment by haraldsteinlechner** [comment]
corruption fixed by https://github.com/aardvark-platform/aardvark.base/commit/640d70fb97ee4eb8fb6dd1647b93e5edd6d7f8e2 as far as i can tell. shall we throw badarchitecture exception in rendering?

**Comment by krauthaufen** [comment]
I thought about that too...
Maybe even in Aardvark.Init (devil, etc. will most likely fail on 32bit anyways)
