### ISSUE TITLE
Aardvark 5.0 changelog

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#45]
The changelog is currently maintained here: https://hackmd.io/58CqcVmnRoGq-X5gIrNThg

My suggestion is to move it to a new wiki page: https://github.com/aardvark-platform/aardvark.docs/wiki
And link it in the ReadMe of aardvark.base: https://github.com/aardvark-platform/aardvark.base

As the ReadMe is actually a general Aardvark overview I'm not sure how to exactly integrate this.
Likewise, we should also link to it from the wiki main page, but I'm also not sure where exactly this would fit best.

We could also extend this changelog and highlight other changes of 5.0:
* New Incremental System
* New Ag System
* Rendering Changes: https://github.com/aardvark-platform/aardvark.rendering/blob/master/ReleaseNotes.txt
* What else?

PS: It would be also nice to introduce a changelog/release notes in every repository that is maintained regularly, e.g. when pushing a new version a summary of notable changes should be added. (not topic of this issue)

**Comment by hyazinthh** [comment]
I've cleaned up the changelog and added a new wiki page: https://github.com/aardvark-platform/aardvark.docs/wiki/Aardvark-5-changelog

It isn't linked anywhere yet, though.

**Comment by hyazinthh** [comment]
The changelogs for 5.0 and 5.1 are linked [here](https://github.com/aardvark-platform/aardvark.docs/wiki#api-documentation) now. Feel free to move it to a more appropriate place.
