### ISSUE TITLE
More float32 data types

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#50]
Ideally all datatypes in Aardvark.Base/Geometry should be available in float and double precision. For rendering applications doing computation in 32-bit precision is sufficient in lots of cases. Of course this a lot of work and continues with intersection tests, special points, and so on. Therefore, we should approach this in multiple steps. As a start, I would go for the most essential primitives like `Ray3f`, `Triangle3f`, `Plane3f`, `Sphere3f`

**Comment by hyazinthh** [comment]
Should be fixed by https://github.com/aardvark-platform/aardvark.base/commit/1ab014d35c58413148b7187f56c38b7b9c0e8f59

Some default epsilon values may not be optimal, still needs testing.
