### ISSUE TITLE
Add Fun.Sinc

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#51]
https://en.wikipedia.org/wiki/Sinc_function

I currently use this local function:
```
static float Sinc(float x)
{
    x = x.Abs();
    if (x < 1e-5f) return 1;
    return Fun.Sin(Constant.PiF * x) / (Constant.PiF * x);
}
```

NOTE: We should evaluate an appropriate epsilon.

**Comment by hyazinthh** [comment]
Added in https://github.com/aardvark-platform/aardvark.base/commit/037aa9da8b88290a2aa45c5472b5191693e5aa7a

Testing directly against zero seems to be sufficient,

**Comment by luithefirst** [comment]
I've also found implementations that only use a 0 check, so if you have also tested this it should be best that way. Also, I guess the `abs` from the code above implementation is only for the epsilon checking. I simply copied it from here: http://www.pbr-book.org/3ed-2018/Sampling_and_Reconstruction/Image_Reconstruction.html

**Comment by luithefirst** [comment]
I also ran the unit test, but also modified it a bit so that it prints the input and output. It turns out that the output sequence starts with 1, then 0.9999 at some point, and then 1 again and not only decreases. Here is the output with ranges of equal output values collapsed:
```
in: 3,8146973E-06 out: 1
in: 0,0001411438 out: 1
in: 0,0001449585 out: 0,99999994
in: 0,00015258789 out: 0,99999994
in: 0,00015640259 out: 1
in: 0,00017547607 out: 1
in: 0,00017929077 out: 0,9999999
in: 0,00020599365 out: 0,9999999
in: 0,00020980835 out: 0,99999994
in: 0,00025558472 out: 0,99999994
in: 0,0002593994 out: 0,9999999
in: 0,00030136108 out: 0,9999999
in: 0,00030517578 out: 0,9999998
in: 0,00030899048 out: 0,9999998
in: 0,00031280518 out: 0,9999999
in: 0,00032043457 out: 0,9999999
in: 0,00032424927 out: 0,99999976
in: 0,00035476685 out: 0,99999976
in: 0,00035858154 out: 0,9999998
in: 0,00038146973 out: 0,9999998
in: 0,00038528442 out: 0,9999997
in: 0,0004119873 out: 0,9999997
in: 0,000415802 out: 0,99999976
in: 0,0004272461 out: 0,99999976
in: 0,0004310608 out: 0,99999964
in: 0,00045013428 out: 0,99999964
in: 0,00045394897 out: 0,9999997
in: 0,00046539307 out: 0,9999997
in: 0,00046920776 out: 0,9999996
in: 0,00047683716 out: 0,9999996
in: 0,00048065186 out: 0,99999964
in: 0,00048446655 out: 0,99999964
```

When calculating a numerical derivative around the epsilon, this will be kind of broken. I actually don't how the behavior of other mathematical functions is and if this might be an issue. Wiki also provides an analytical derivative, so this could be used then. Should we close the issue?

**Comment by hyazinthh** [comment]
I think we should use an epsilon then, so that for all `x` with `|x| > eps` we have `sinc(x) < 1`. Since there is an analytical derivative, I don't think this should be a problem. In any case, the numerical derivative is broken with this version as well.

**Comment by hyazinthh** [comment]
Another issue might be that the implementation is not monotone. I.e. there is no guarantee that `sinc(x) > sinc(y)` when `|x| < |y|`. I'm not sure if this can be prevented, this seems to happen even for quite large input numbers.

**Comment by luithefirst** [comment]
Yes, thats what I wanted to point out with the listed sequence and I'm not even sure if this becomes monotone at some point. So if this is not only an issue around a certain epsilon, it still might be best to stick with just a 0 check.

**Comment by hyazinthh** [comment]
The thing is that with an epsilon we can at least make sure that `sin(x) = 1` if `|x|` is within that epsilon. The unit test actually already makes it possible to determine the epsilon. The question is if that property is wanted.

**Comment by luithefirst** [comment]
I'm not sure either. The epsilon used by the pbrt implementation would also not give this property. As you have already spent time figuring this out, it's nice to provide at least this property.

I guess the true solution would be to implement a direct approximation of the sinc function using some kind of series approximation or lookup tables, similar to like the other mathematical functions are implemented. This would be of course way of the top. From my point, this issue is solved and we have all the tools and insight to come back if needed.

**Comment by krauthaufen** [comment]
Why not use simply use double arithmetics? Whenever `sin x / x` is NaN or infinite it should be `1`
That's the best value you get in double apartment from using a different calculation altogether like taylor expansions, etc

**Comment by krauthaufen** [comment]
And it works independent of the floating type used
