### ISSUE TITLE
Exclude assemblies from Introspection and Plugin loading

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#52]
It would be nice to be able to specify certain names or regexes to be excluded from Plugin or Introspection loading. At the moment we have hardcoded list or prefixes. I would like to exclude my project specific 3rd party libraries and libraries from my company partner. 

A first time `Aardvark.Init()` of my app takes 40s because there is a huge number of assemblies and logs about 1500 lines. Successive runs then take about 4s still and there are also 1500 lines.

**Comment by haraldsteinlechner** [comment]
100% agreed!

Introspection.AssemblyFilter :: Assembly -> bool?

**Comment by luithefirst** [comment]
Yes, a filter function would be a nice extension that fits well with the current list of hardcoded conditions.

**Comment by luithefirst** [comment]
`GetPluginAssemblyPaths()` does not use any filter and on first startup loads **all** assemblies in the startup directory. 
For me, it would make sense to also apply the filter there. 

For the Introspection cache, there are actually two places where assemblies are excluded:
https://github.com/aardvark-platform/aardvark.base/blob/master/src/Aardvark.Base/Introspection/Introspection.cs#L170
https://github.com/aardvark-platform/aardvark.base/blob/master/src/Aardvark.Base/Introspection/Introspection.cs#L307
It would also make sense to clean up the default exclusions after refactoring. 

Having only one filter for Introspection and Plugins should be enough?

**Comment by haraldsteinlechner** [comment]
think so. either both or nothing - simpler and if you want one the other one is affordable.

**Comment by hyazinthh** [comment]
https://github.com/aardvark-platform/aardvark.base/commit/ad3de014234a1e323787cd6bd847a9f95a927df3 adds `IntrospectionProperties.CustomAssemblyFilter` and `IntrospectionProperties.IgnoreDefaultAssemblyFilter`. The former let's you add a custom filter while the latter property makes it possible to disable the built-in filter (in case that is ever needed).

**Comment by luithefirst** [comment]
We should still review the logging output of this process. When starting my app there are 6 introspection queries + plugins, each ignoring the same files. With now logging when a file is ignored, I would expect that there is still a similar amount of log entries. Maybe we want to simply allow adding entries to the "ignore" dict. If we only use the filter function, caching would not be "clean" as the filter could be changed.

I also just ran a benchmark on a system with a quite fast SDD (>1000MB/s sequential write) and logging 200 lines takes more than 100ms (all 10 times):
````
var names = Directory.EnumerateFiles(".").ToArray();
for (int i = 0; i < 10; i++)
{
	Thread.Sleep(1000);
	Report.BeginTimed("ALL");
	foreach (var j in names)
		Report.Line("foo name bla report line test with format {0}", j);
	Report.End();
}
```
From the logging alone I would have 7x 100ms startup time.

Btw, after the first startup, 661 files are created in the cache directory at the moment. I would expect this to now be much less when I can use an ignore filter. Maybe, we still want to discuss an alternative cache structure.
