### ISSUE TITLE
Add vector swizzle property setters

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#56]
It would nice to allow using the swizzle properties as setters:
```
var vec = V3d.III;
vec.XY = V2d.OO;
```
This would be also convenient for shaders where I currently use this workaround:
```
[<GLSLIntrinsic("{0} = {1}")>] [<KeepCall>]
let set (a: 'a) (b : 'a) = onlyInShaderCode "set" 
...
set va.XYZ value
```

**Comment by hyazinthh** [comment]
Added setters in v51 for properties without constants and without duplicates. E.g. a setter for `V4d.XX` would not make much sense. Let me know if I missed anything.
