### ISSUE TITLE
NativeAssemblyLoading - regression with isolated loads

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.base#64]
our new netcoreapp3.1 native lib sheme is no longer compatible with https://github.com/aardvark-platform/aardvark.base/blob/544aecc388f1ad93eb4f965f30780462189b2cb6/src/Aardvark.Base/Introspection/Introspection.cs#L1356

this is for example used by https://github.com/aardvark-platform/aardvark.rendering/blob/1aa1f68be058894b699972735b210d01efcb348b/src/Aardvark.SceneGraph.IO/IO.fs#L19 - which is broken since then.

@luithefirst  @hyazinthh 

cleanest way is to deprecate the field?

**Comment by krauthaufen** [comment]
Yep, should definitely not use that, temp also was a bad location for these things anyways

**Comment by haraldsteinlechner** [comment]
marked obsolete - remove in next major version
