### ISSUE TITLE
Aardvark.PixImage.FreeImage

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#67]
I'm still using FreeImage from our internal repository and it would be nice to update this and make it .net core compatible. Ideally, using dual build targets.

The .net wrapper "FreeImageNET.dll" (net framework xx) and the native libs are pre-built there. The native libs are packed to the FreeImageNet assembly and included in the Aardvark.VRVis.Images packages.

My suggestion would be to fork the FreeImageNET wrapper (https://sourceforge.net/p/freeimage/svn/HEAD/tree/FreeImage/trunk/Wrapper/FreeImage.NET/cs/) in Aardvark Community (with pre-built native libs) and extend it with our build script and define net framework and net core build targets (should be possible, see: https://github.com/matgr1/FreeImage-dotnet-core). This would then be similar to DevilSharp or Aardvark.Embree. I assume that we can use any open-source license there. In this case, it requires the GPL2/3 and the FreeImage Public License.

I'm not sure if we then can move the PixImage loader to Aardvark.PixImage.FreeImage project in Aardvark.Base, because of the incompatible license. Having it in Base too would make changes and refactoring easier in the future. In the repository itself, we do not include any binary or code and it might only need to be considered when using it in an application? Otherwise, we would need to move the Aardvark.PixImage.FreeImage bindings to Aardvark Community repository as well as a separate repository so we can update it together with every major base version, but such lonely repositories are not very maintenance friendly. Any thoughts?

**Comment by hyazinthh** [comment]
Moved here: https://github.com/aardvark-platform/Aardvark.PixImage.FreeImage
