### ISSUE TITLE
ComputeMD5Hash should compute md5 hash

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.base#72]
We have changed all MD5 uses to SHA1 since there were issues when running in WASM.

This was done in a quick hack and we should review this. It seems that there were only two uses, one in Introspection and one in ArrayExtensions (ComputeMD5Hash). I think ComputeMD5Hash should still calculate MD5 hashes as before and since this is a utility method I would see the responsibility on the user side. ComputeMD5Hash is rarely used in all Aardvark libraries (1 in Base, 0 uses in Rendering), and if so we could change it in the relevant places, e.g. in String.ToGuid() which we should change to SHA1 there and also update all comments accordingly.

**Comment by hyazinthh** [comment]
Fixed by https://github.com/aardvark-platform/aardvark.base/commit/3cf214501067a2344dfec34783e07b34f1425db0
