### ISSUE TITLE
Can this work with dotNET MAUI?

### ISSUE THREAD

**Issue by asheesh1996** [aardvark-platform/aardvark.base#76]
Hi, 
I wanted to know if it is possible to render the 3d window output from aardvark library in dotNET maui windowing?

**Comment by krauthaufen** [comment]
Not yet at least, it also depends on which platform you'd want to render (android/ios/windows/macos/etc.)

**Comment by asheesh1996** [comment]
Windows and Mac

**Comment by haraldsteinlechner** [comment]
for native windowing in aardvark.rendering we mostly moved to windowing interoperability using glfw and SILK.net which means most likely aardvark could build maui support on top of https://github.com/dotnet/Silk.NET/issues/849. also note that the native windowing code and the current backends can be found here: https://github.com/aardvark-platform/aardvark.rendering/tree/master/src/Application

that said, most aardvark applications don't use native windowing but render into a website using [aardvark.media](https://github.com/aardvark-platform/aardvark.media) and use for example [aardium](https://github.com/aardvark-community/aardium) on desktop environments to render the page.

**Comment by haraldsteinlechner** [comment]
Just to get back to this - did you go via aardvark.rendering or via the aardium/aardvark.media then? i would close this as there was no demand for direct MAUI controls so far. Please feel free to-reopen if need pops up again.
