### ISSUE TITLE
Vulnerability in ImageSharp dependency

### ISSUE THREAD

**Issue by madorjan** [aardvark-platform/aardvark.base#82]
The currently used SixLabors.ImageSharp version has a vulnerability, which produces following compiler warning:
``NU1903	Warning As Error: Package 'SixLabors.ImageSharp' 2.1.6 has a known high severity vulnerability, https://github.com/advisories/GHSA-65x7-c272-7g7r``

SixLabors.ImageSharp should be updated to 3.1.3.

**Comment by hyazinthh** [comment]
Apparently, they backported the fix and released [2.1.7](https://www.nuget.org/packages/SixLabors.ImageSharp/2.1.7). You should be able to use that without requiring a new Aardvark.Base version. Still, it might be a good idea to move to 3.X eventually.

**Comment by madorjan** [comment]
OK, then I think an update to 2.1.7 would bei sufficient 👍
